# Generated by Django 4.1.3 on 2022-11-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='photos/%d/%m/%Y/')),
                ('name_person', models.CharField(max_length=15)),
                ('contacts', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
