# Generated by Django 4.1.3 on 2022-11-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sales_options_alter_sales_contacts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=80, verbose_name='Тип аренды')),
            ],
            options={
                'verbose_name': 'Тип аренды',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='sales',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.category'),
        ),
    ]
