# Generated by Django 4.1.3 on 2022-11-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_category_sales_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=80, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Текст объявления'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
